eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://:8761/eureka
server:
  port: 8090
spring:
  application:
    name: employee
  datasource:
    url: jdbc:mysql://db:3306/task2db
    username: root
    password: shereen12003773
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
management:
  tracing:
    sampling:
      probability: 1.0

