eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/employee/**
            - Path=/api/v2/employee/**
        - id: address
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/address/**
        - id: department
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/department/**
management:
  tracing:
    sampling:
      probability: 1.0

